name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/41tair/net-debug:latest
    - name: Login to ghcr
      run: export CR_PAT=${{ secrets.GHCR_TOKEN }}; echo $CR_PAT | docker login ghcr.io -u 41tair --password-stdin
    - name: Push to registry
      run: docker push ghcr.io/41tair/net-debug:latest
